insert into telas(id, descricao) values (1, 'Unidades');
insert into telas(id, descricao) values (2, 'Características');
insert into telas(id, descricao) values (3, 'Armazéns');
insert into telas(id, descricao) values (4, 'Locais de estoque');
insert into telas(id, descricao) values (5, 'Grupos de produtos');
insert into telas(id, descricao) values (6, 'Produtos');
insert into telas(id, descricao) values (7, 'Kit de produtos');
insert into telas(id, descricao) values (8, 'Produtos x Características');
insert into telas(id, descricao) values (9, 'Produtos x Locais de estoque');
insert into telas(id, descricao) values (10, 'Cadastro de unidades');
insert into telas(id, descricao) values (11, 'Devolução para fornecedor');
insert into telas(id, descricao) values (12, 'Saída para revendedor');
insert into telas(id, descricao) values (13, 'Solicitação de compras');
insert into telas(id, descricao) values (14, 'Pedidos de compra');
insert into telas(id, descricao) values (15, 'Fornecedores');
insert into telas(id, descricao) values (16, 'Produtos x Fornecedor');
insert into telas(id, descricao) values (17, 'Grupos de produto x Fornecedor');
insert into telas(id, descricao) values (18, 'Documento de entrada');
insert into telas(id, descricao) values (19, 'Tipos de movimento');
insert into telas(id, descricao) values (20, 'Classes de imposto');
insert into telas(id, descricao) values (21, 'Formas de pagamento');
insert into telas(id, descricao) values (22, 'Operadoras de cartão');
insert into telas(id, descricao) values (23, 'Bancos');
insert into telas(id, descricao) values (24, 'Contas bancárias');
insert into telas(id, descricao) values (25, 'Caixas');
insert into telas(id, descricao) values (26, 'Planos de conta');
insert into telas(id, descricao) values (27, 'Tabelas de preço');
insert into telas(id, descricao) values (28, 'Lançamento de movimentos (Genérico)');
insert into telas(id, descricao) values (29, 'Pedidos de venda');
insert into telas(id, descricao) values (30, 'Venda rápida');
insert into telas(id, descricao) values (31, 'Contas a pagar');
insert into telas(id, descricao) values (32, 'Contas a receber');
insert into telas(id, descricao) values (33, 'Documento de saída');
insert into telas(id, descricao) values (34, 'Funcionários');
insert into telas(id, descricao) values (35, 'Cargos');
insert into telas(id, descricao) values (36, 'Turnos');
insert into telas(id, descricao) values (37, 'Benefícios');
insert into telas(id, descricao) values (38, 'Funcionários x Cargos');
insert into telas(id, descricao) values (39, 'Funcionários x Turnos');
insert into telas(id, descricao) values (40, 'Funcionários x Benefícios');
insert into telas(id, descricao) values (41, 'Empresa');
insert into telas(id, descricao) values (42, 'Usuários');
insert into telas(id, descricao) values (43, 'Grupos de usuários');
insert into telas(id, descricao) values (44, 'Grupos x Permissões');

